repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '.*\.patch$'
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Python
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
